"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Cliente_1 = require("./Cliente");
const Empregado_1 = require("./Empregado");
const Pessoa_1 = require("./Pessoa");
let pessoa1 = new Pessoa_1.Pessoa('reygis', 33, 'Sergipe', 'Aracaju');
pessoa1.apresentar();
let pessoa2 = new Pessoa_1.Pessoa('Silvia', 45, 'São Paulo', 'São Paulo');
pessoa2.apresentar();
let cliente1 = new Cliente_1.Cliente('Coisildo', 50, 'Brasilia', 'DF', true);
cliente1.apresentar();
cliente1.verificarAssinatura();
let empregado1 = new Empregado_1.Empregado('Coisildo', 34, 'São paulo', 'Uberlandia');
empregado1.apresentar();
empregado1.contrato();
